export default [
  // 根路径重定向到登录页
  {
    path: '/',
    redirect: '/h5/login',
  },
  {
    path: '/',
    redirect: '/h5/login',
    exact: true,
  },
  {
    path: '/h5',
    component: '@/layouts/H5Layout',
    routes: [
      // 公开页面（无需登录）
      {
        path: '/h5/login',
        component: '@/pages/h5/Login',
        exact: true,
        title: '登录',
      },
      {
        path: '/h5/register',
        component: '@/pages/h5/Register',
        exact: true,
        title: '注册',
      },
      {
        path: '/h5/qr-pay/:token',
        component: '@/pages/h5/QrPay',
        exact: true,
        title: '扫码支付',
      },
      {
        path: '/h5/collection/pay/:token',
        component: '@/pages/h5/CollectionPay',
        exact: true,
        title: '收款',
      },

      // 需要登录的页面
      {
        path: '/h5/payment-password/setup',
        component: '@/pages/h5/PaymentPasswordSetup',
        exact: true,
        title: '设置支付密码',
        auth: true,
      },
      {
        path: '/h5/payment-password/change',
        component: '@/pages/h5/PaymentPasswordChange',
        exact: true,
        title: '修改支付密码',
        auth: true,
      },
      {
        path: '/h5/home',
        component: '@/pages/h5/Home',
        exact: true,
        title: '首页',
        auth: true,
      },
      {
        path: '/h5/settings',
        component: '@/pages/h5/Settings',
        exact: true,
        title: '设置',
        auth: true,
      },
      {
        path: '/h5/settings/change-login-password',
        component: '@/pages/h5/ChangeLoginPassword',
        exact: true,
        title: '修改登录密码',
        auth: true,
      },
      {
        path: '/h5/settings/about',
        component: '@/pages/h5/About',
        exact: true,
        title: '关于',
        auth: true,
      },
      {
        path: '/h5/transfer',
        component: '@/pages/h5/Transfer',
        exact: true,
        title: '转账',
        auth: true,
      },
      {
        path: '/h5/transfer/confirm',
        component: '@/pages/h5/TransferConfirm',
        exact: true,
        title: '确认转账',
        auth: true,
      },
      {
        path: '/h5/transfer/result/:id',
        component: '@/pages/h5/TransferResult',
        exact: true,
        title: '转账结果',
        auth: true,
      },
      {
        path: '/h5/ai-talk',
        component: '@/pages/h5/AITalk',
        exact: true,
        title: '招财喵',
        auth: true,
      },
      {
        path: '/h5/scan',
        component: '@/pages/h5/Scan',
        exact: true,
        title: '扫一扫',
        auth: true,
      },
      {
        path: '/h5/contacts',
        component: '@/pages/h5/Contacts',
        exact: true,
        title: '联系人',
        auth: true,
      },
      {
        path: '/h5/friend-requests',
        component: '@/pages/h5/FriendRequests',
        exact: true,
        title: '新朋友',
        auth: true,
      },
      {
        path: '/h5/profile',
        component: '@/pages/h5/Profile',
        exact: true,
        title: '我的',
        auth: true,
      },
      {
        path: '/h5/profile-detail',
        component: '@/pages/h5/ProfileDetail',
        exact: true,
        title: '个人详情',
        auth: true,
      },
      {
        path: '/h5/qr-pay/receipt/:id',
        component: '@/pages/h5/QrPayReceipt',
        exact: true,
        title: '支付回执',
        auth: true,
      },
      {
        path: '/h5/collection',
        component: '@/pages/h5/Collection',
        exact: true,
        title: '收款',
        auth: true,
      },
      {
        path: '/h5/collection/result/:id',
        component: '@/pages/h5/CollectionResult',
        exact: true,
        title: '转账结果',
        auth: true,
      },
      {
        path: '/h5/collection/request/:id',
        component: '@/pages/h5/CollectionRequest',
        exact: true,
        title: '收款请求',
        auth: true,
      },
      {
        path: '/h5/account/transactions',
        component: '@/pages/h5/Transactions',
        exact: true,
        title: '账单',
        auth: true,
      },
      {
        path: '/h5/recharge',
        component: '@/pages/h5/BankCardRecharge',
        exact: true,
        title: '充值',
        auth: true,
      },
      {
        path: '/h5/withdraw',
        component: '@/pages/h5/BankCardWithdraw',
        exact: true,
        title: '提现',
        auth: true,
      },
      {
        path: '/h5/credit',
        component: '@/pages/h5/Credit',
        exact: true,
        title: 'Mini花呗',
        auth: true,
      },
      {
        path: '/h5/credit/bills',
        component: '@/pages/h5/CreditBills',
        exact: true,
        title: '账单',
        auth: true,
      },
      {
        path: '/h5/credit/bills/:id',
        component: '@/pages/h5/CreditBillDetail',
        exact: true,
        title: '账单详情',
        auth: true,
      },
      {
        path: '/h5/credit/repay',
        component: '@/pages/h5/CreditRepay',
        exact: true,
        title: '还款',
        auth: true,
      },
      {
        path: '/h5/wallet',
        component: '@/pages/h5/Wallet',
        exact: true,
        title: '充值提现',
        auth: true,
      },
      {
        path: '/h5/bank-cards',
        component: '@/pages/h5/BankCards',
        exact: true,
        title: '银行卡',
        auth: true,
      },
      {
        path: '/h5/bank-cards/add',
        component: '@/pages/h5/BankCardAdd',
        exact: true,
        title: '注册银行卡',
        auth: true,
      },
      {
        path: '/h5/bank-cards/:id',
        component: '@/pages/h5/BankCardDetail',
        exact: true,
        title: '卡片详情',
        auth: true,
      },
      {
        path: '/h5/bank-cards/:id/bills',
        component: '@/pages/h5/BankCardBills',
        exact: true,
        title: '卡账单',
        auth: true,
      },
      {
        path: '/h5/bank-cards/:id/recharge',
        component: '@/pages/h5/BankCardRecharge',
        exact: true,
        title: '充值',
        auth: true,
      },
      {
        path: '/h5/bank-cards/:id/withdraw',
        component: '@/pages/h5/BankCardWithdraw',
        exact: true,
        title: '提现',
        auth: true,
      },
      {
        path: '/h5/bank-card-bind',
        component: '@/pages/h5/BankCardBind',
        exact: true,
        title: '绑定银行卡',
        auth: true,
      },
      {
        path: '/h5/identity-bind',
        component: '@/pages/h5/IdentityBind',
        exact: true,
        title: '身份绑定',
        auth: true,
      },
      {
        path: '/h5/settings/version',
        component: '@/pages/h5/VersionInfo',
        exact: true,
        title: '版本信息',
        auth: true,
      },
      {
        path: '/h5/settings/user-agreement',
        component: '@/pages/h5/UserAgreement',
        exact: true,
        title: '用户协议',
        auth: true,
      },
      {
        path: '/h5/settings/privacy-policy',
        component: '@/pages/h5/PrivacyPolicy',
        exact: true,
        title: '隐私政策',
        auth: true,
      },

      // 默认跳转
      {
        path: '/h5',
        redirect: '/h5/login',
      },
    ],
  },
];
